import { LegalBody } from "@/components/legal/LegalBody";
import { LegalHero } from "@/components/legal/LegalHero";
import { LegalRow, LegalRowDivider } from "@/components/legal/LegalRow";
import { Container } from "@/components/ui";
import type { BrowserLink, CookieSection } from "@/data/legal-cookies";

const heroImage = { src: "/images/legal-hero-banner-2880x700.webp", width: 2880, height: 700 };

/** Cookie declaration, pixel-matched to Figma 1269:1037. */
export function CookiePage({ sections, browserLinks }: { sections: CookieSection[]; browserLinks: BrowserLink[] }) {
  return (
    <>
      <LegalHero eyebrow="Cookie policy" heading="Cookie declaration" image={heroImage} />
      <Container className="pb-[50px] pt-10 xl:pb-0 xl:pt-0">
        <div>
          {sections.map((section, i) => (
            <div key={section.id}>
              {i > 0 && <LegalRowDivider />}
              <LegalRow heading={section.heading}>
                <LegalBody body={section.body} />
                {section.id === "manage-cookie-preferences" && (
                  <ul className="mt-4 flex flex-col gap-4 font-sans text-body">
                    {browserLinks.map((link) => (
                      <li key={link.name}>
                        {link.name}:{" "}
                        <a href={link.href} target="_blank" rel="noopener noreferrer" className="underline">
                          {link.href}
                        </a>
                      </li>
                    ))}
                    <li>If you are using any other web browser, please visit your browser’s official support documents.</li>
                    <li>
                      Cookie Policy Generated By{" "}
                      <a href="https://www.cookieyes.com/" target="_blank" rel="noopener noreferrer" className="underline">
                        CookieYes - Cookie Policy Generator
                      </a>
                      .
                    </li>
                  </ul>
                )}
              </LegalRow>
            </div>
          ))}
        </div>
      </Container>
    </>
  );
}
