import Link from "next/link";
import { Container } from "@/components/ui";
import type { CookieCategory } from "@/data/legal-cookies";

/**
 * Cookie declaration. Unlike FAQ/Terms/Privacy, the live page's actual cookie table is generated by a
 * client-side consent widget and never appears in static HTML (plan section 4/6) — so the specific cookie
 * names, providers and durations could not be extracted and are not fabricated here. The categories below are
 * genuine content (the standard groupings such widgets use); the callout says plainly what is missing.
 */
export function CookiePage({ intro, categories }: { intro: string; categories: CookieCategory[] }) {
  return (
    <Container className="py-[50px]">
      <div className="mx-auto flex max-w-narrow flex-col gap-10">
        <div>
          <h1 className="text-[36px] leading-[44px] xl:text-display">Cookie declaration</h1>
          <div aria-hidden="true" className="mt-8 h-px w-full bg-sand" />
          <p className="mt-8 font-sans text-body">{intro}</p>
        </div>

        <div role="note" className="border-[0.5px] border-terracotta bg-terracotta/10 p-5">
          <p className="font-display text-label font-medium text-ink">NEEDS CONFIRMATION</p>
          <p className="mt-2 font-sans text-body">
            The live cookie table (individual cookie names, the third party that sets each one, and how long it lasts) is
            rendered by a script after the page loads, so it can’t be read from the page’s source and isn’t reproduced
            here. Pull it from{" "}
            <a href="https://anitaslist.com/pages/cookies-declaration" target="_blank" rel="noopener noreferrer" className="underline">
              the live page
            </a>{" "}
            with a browser open, or from your consent-management dashboard, and it can be dropped straight into{" "}
            <code className="font-mono text-meta">src/data/legal-cookies.ts</code>.
          </p>
        </div>

        <div className="flex flex-col gap-8">
          {categories.map((cat) => (
            <section key={cat.id}>
              <h2 className="font-display text-h3 font-medium">{cat.title}</h2>
              <p className="mt-2 font-sans text-body">{cat.description}</p>
            </section>
          ))}
        </div>

        <p className="font-sans text-body">
          You can change your cookie choices at any time. Questions about this page can be sent to{" "}
          <Link href="mailto:team@anitaslist.com" className="underline">
            team@anitaslist.com
          </Link>
          .
        </p>
      </div>
    </Container>
  );
}
