/**
 * Cookie declaration content. Previously unavailable (the live page's cookie table is rendered by a client-side
 * consent widget and never appears in static HTML), but the new Figma design (1269:1037) draws the real,
 * CookieYes-generated policy narrative in full - see the "Cookie Policy Generated By CookieYes" credit in the
 * last section - so that real copy replaces the old placeholder category table.
 */
export type CookieSection = { id: string; heading: string; body: string };
export type BrowserLink = { name: string; href: string };

export const cookieSections: CookieSection[] = [
  {
    id: "what-are-cookies",
    heading: "What are cookies?",
    body:
      "This Cookie Policy explains what cookies are and how we use them, the types of cookies we use i.e, the information we collect using cookies and how that information is used, and how to manage the cookie settings.\n\nCookies are small text files that are used to store small pieces of information. They are stored on your device when the website is loaded on your browser. These cookies help us make the website function properly, make it more secure, provide better user experience, and understand how the website performs and to analyse what works and where it needs improvement.",
  },
  {
    id: "how-we-use-cookies",
    heading: "How do we use cookies?",
    body:
      "As most of the online services, our website uses first-party and third-party cookies for several purposes. First-party cookies are mostly necessary for the website to function the right way, and they do not collect any of your personally identifiable data.\n\nThe third-party cookies used on our website are mainly for understanding how the website performs, how you interact with our website, keeping our services secure, providing advertisements that are relevant to you, and all in all providing you with a better and improved user experience and help speed up your future interactions with our website.",
  },
  {
    id: "manage-cookie-preferences",
    heading: "Manage cookie preferences",
    body:
      "You can change your cookie preferences any time by clicking the above button. This will let you revisit the cookie consent banner and change your preferences or withdraw your consent right away.\n\nIn addition to this, different browsers provide different methods to block and delete cookies used by websites. You can change the settings of your browser to block/delete the cookies. Listed below are the links to the support documents on how to manage and delete cookies from the major web browsers.",
  },
];

export const browserCookieLinks: BrowserLink[] = [
  { name: "Chrome", href: "https://support.google.com/accounts/answer/32050" },
  { name: "Safari", href: "https://support.apple.com/en-in/guide/safari/sfri11471/mac" },
  {
    name: "Firefox",
    href: "https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&redirectlocale=en-US",
  },
  {
    name: "Internet Explorer",
    href: "https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc",
  },
];
